# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Caracteristica')),
            ],
            options={
                'verbose_name_plural': 'Caracteristicas',
                'verbose_name': 'Caracteristica',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted', models.BooleanField(default=False, verbose_name='eliminado')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
                ('deleted', models.BooleanField(default=False, verbose_name='eliminado')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('order', models.ForeignKey(help_text='Pedido', on_delete=django.db.models.deletion.CASCADE, to='products.Order', verbose_name='Pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='En inventario')),
                ('image', models.ImageField(upload_to='media', verbose_name='Imagen')),
                ('feature', models.ManyToManyField(to='products.Feature')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.AddField(
            model_name='ordersale',
            name='product',
            field=models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(help_text='Producto(s)', through='products.OrderSale', to='products.Product', verbose_name='Producto(s)'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
