# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(help_text='Producto(s)', related_name='sale', through='products.OrderSale', to='products.Product', verbose_name='Producto(s)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Precio'),
        ),
    ]
