# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20160927_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordersale',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(default=1, help_text='Venta', on_delete=django.db.models.deletion.CASCADE, to='products.OrderSale', verbose_name='Venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersale',
            name='user',
            field=models.ForeignKey(default=1, help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ordersale',
            name='product',
        ),
        migrations.AddField(
            model_name='ordersale',
            name='product',
            field=models.ManyToManyField(help_text='Producto(s)', through='products.Order', to='products.Product', verbose_name='Producto(s)'),
        ),
    ]
