# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160927_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersale',
            old_name='product',
            new_name='products',
        ),
    ]
